# Generated by Django 3.1 on 2020-10-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentApi',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeApi',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_date', models.DateField()),
                ('emp_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp2_apiview.departmentapi')),
            ],
        ),
    ]
