# Generated by Django 3.1 on 2020-10-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=20)),
                ('dep_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_date', models.DateTimeField()),
                ('emp_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp1.department')),
            ],
        ),
    ]
