# Generated by Django 3.1 on 2020-10-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('frnd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('frnd_name', models.CharField(max_length=50)),
                ('frnd_email', models.EmailField(max_length=254)),
                ('frnd_dob', models.DateField()),
                ('frnd_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.city')),
            ],
        ),
    ]
